### PR TITLE
Fix uwsgi.service to start cron in the web container

### PR DESCRIPTION
**Pull request by paramsingh**
We explicitly stop cron in the Dockerfile so that it doesn't run in all the containers.

But I missed starting it up in the web container

### CODE REVIEW

**Comment by paramsingh** [comment]
@brainzbot retest this please.

**Comment by paramsingh** [comment]
@brainzbot retest this please

**Comment by alastair** [comment]
Looking through the AB `Dockerfile.prod` file I have a few further followups:

* We install `cron` when installing the dependencies (line16), this probably isn't needed as it's already installed by the baseimage?
* Where is the `down` file for cron added? I've looked in `metabrainz/python:2.7` and it's not there, and I can't see anything in the Dockerfile that adds it, so...?
* Where is the cron configuration added? I don't see anything in the Dockerfile to add this

**Comment by alastair** [comment]
@paramsingh with the changes to #319 we probably need to make a few changes here regarding the way that the Dockerfile is set up. What are your thoughts? Should we get a quick release out with these changes, or should we attack this issue with service names and configuration files? I'd rather that we fix this properly now, should we plan to fix this together some time this week?

**Comment by alastair** [comment]
Actually, I'm confused by this now.. I think this PR has lost a few commit, I guess someone merged the updates to Dockerfile by mistake? I only see a small fix here now to run cron as a second container. Is cron already running in production in the web container?

**Comment by paramsingh** [comment]
Closing in favor of #329

**Pull request closed without merging**
