### PR TITLE
AB-414: Build Annoy indices using computed similarity metrics

### PR DESCRIPTION
**Pull request by aidanlw17**
# AB-414: Build Annoy indices using computed similarity metrics

This pull request introduces functionality to build and query indices for the similarity metrics using cli scripts.

### Annoy Index Model
- Uses a class to wrap the annoy index, includes functionality to create, build, save, and load an index,
  whether it is existing or not. Using this wrapper, items can also be added to the index. Once an index 
  is in the loaded state, functionality from this class allows for it to be queried.

### Incrementally Add Items to Annoy Index
- Uses a cli script to create and delete indices, as well as add all items in the database for which a 
  similarity metric has been computed:
  `./develop.sh run --rm webserver python2 manage.py similarity add-index <metric_name>`

### Scripts to Query Annoy and Postgres
- Scripts that query Postgres and Annoy for similar recordings and detect the number of intersections 
  between the two solutions.

### Utilities
- Additional utilities to get all metrics or Annoy indices that have been computed, and to query for 
  similar recordings using the Postgres indices.

### CODE REVIEW

**Comment by aidanlw17** [comment]
@alastair to make this PR I created a new branch from the one used by #353, in order to build on the changes that it introduces. However, this PR now also includes all of the commits from #353 which was not my intention. Do you know how I can exclude those from this PR?

**Comment by paramsingh** [comment]
I don't think that should be a problem for now, once #353 gets merged, you can rebase this over master and only the commits not in #353 will show up.

**Comment by aidanlw17** [comment]
thanks @paramsingh!

**Comment by alastair** [comment]
alternatively, you can say that you want to merge this into the branch of #353 (instead of master), and then it'll only show those commits. Try the edit button at the top of the PR and see if you can (I'm not sure if it's possible because your work is on a branch in your fork). If not, don't worry, as @paramsingh says

**Comment by aidanlw17** [comment]
Closed as the content of this PR is covered in #364.

**Pull request closed without merging**
