### PR TITLE
Specified private_network IP address in Vagrantfile for remote debugging

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by alastair** [comment]
what does this do?

**Comment by gentlecat** [comment]
This allows to connect to Python inside a Vagrant VM using remote debugger. See https://www.jetbrains.com/pycharm/help/remote-debugging.html for example.

**Comment by alastair** [comment]
Sure. You don't need to ask about these simple changes if they solve a problem for you

**Comment by gentlecat** [comment]
OK. Thanks.

**Pull request merged**
