### PR TITLE
AB-334: MB database image setup in AB and fetch data for recording entity

### PR DESCRIPTION
**Pull request by rsh7**
Added a container of the [image](https://github.com/metabrainz/musicbrainz-server/blob/master/docker/templates/Dockerfile.test-database.m4) in AB in order to test using MB data at the scale of AcousticBrainz. The volume for the container is specified to be `acousticbrainz-server/data/mbdata.` Access the MB database directly for `recording` entity without use of web service.

Instructions to import the data:
To import the database dumps in a single command, use: docker-compose -f docker/docker-compose.dev.yml run musicbrainz_database

### CODE REVIEW

**Comment by paramsingh** [comment]
I'm not sure if we want to merge this into master or if we want to create new branches for each of the two methods of direct db access we're considering. @alastair ?

**Comment by paramsingh** [comment]
Also, you should fix tests for this, I guess we'd have to write new tests for the musicbrainz_db module?

**Comment by rsh7** [comment]
@paramsingh , Yeah I would add tests to the musicbrainz_database module.

**Comment by rsh7** [comment]
There should be separate PR's for image setup and use of MB database in AB. And we would use Brainzutils to access database for different entities. 
Closing this.

**Pull request closed without merging**
