### PR TITLE
Added more logging handlers

### PR DESCRIPTION
**Pull request by gentlecat**
* Email (SMTPHandler)
* [Sentry](https://github.com/getsentry/sentry) ([Raven](https://github.com/getsentry/raven-python))

:memo:

### CODE REVIEW

**Comment by gentlecat** [comment]
We use Sentry in MetaBrainz website and CritiqueBrainz already. It works quite well, makes keeping track of problems easier.

**Comment by gentlecat** [comment]
Also it doesn't look like we do any logging in other parts of the server. I can look into that as well.

**Comment by alastair** [comment]
What log systems do you suggest we set up in production? All of them? Do we have a metabrainz sentry server? Who will get emails?

**Comment by gentlecat** [comment]
*SMTPHandler* sends email for every single exception that occurs. Sentry notifications are [less reduandant](https://docs.getsentry.com/on-premise/notifications/). I'm running it on my own server since nobody wanted to deploy another application on MusicBrainz servers.

**Comment by alastair** [comment]
Yeah, i've used sentry a bit. It's nice. Let's use your instance for now, but I would feel happier moving it somewhere else in the future, especially since we have 3 (?) products now using it.

**Comment by alastair** [comment]
go for it, and set me up a sentry login, please :)

**Comment by gentlecat** [comment]
Yeah, I agree with you. Should poke @mayhem about that once again.

**Comment by gentlecat** [comment]
@alastair, you should receive an invitation via email (might be in spam).

**Pull request merged**
