### PR TITLE
AB-110: Link recordings in a class to their AB page

### PR DESCRIPTION
**Pull request by dufferzafar**
[Ticket](http://tickets.musicbrainz.org/browse/AB-110)

### CODE REVIEW

**Comment by gentlecat** [comment]
Do these open in a new page/tab by default?

**Comment by dufferzafar** [comment]
No, they don't. Let me just push up the fix.

**Comment by dufferzafar** [comment]
@gentlecat I've made the change :)

**Comment by alastair** [comment]
Looks good, thanks

**Pull request merged**
