### PR TITLE
AB-120: Schema changes for challenges

### PR DESCRIPTION
**Pull request by gentlecat**
This is based on admin stuff and snapshot changes, so look at that first.

### CODE REVIEW

**Comment by gentlecat** [comment]
Admin stuff is also required for this.

**Comment by alastair** [comment]
how does does PR work with #188?

**Comment by gentlecat** [comment]
What do you mean? It depends on it (snapshot table).

**Comment by alastair** [comment]
Right, except both PRs merge to master, and this PR contains commit 3bc3b55d49562fdb875972597155a86efb03a877, which makes it difficult to see the specific changes made in the other commit (OK, github has the option to select a single commit to view, but you get my point). I was just curious as to why this PR had both commits, or wasn't configured to merge to the #188 branch, for example.

**Comment by alastair** [comment]
This is fine :+1:, merge/rebase as you wish

**Comment by gentlecat** [comment]
Rebased and merged.

**Pull request merged**
