### PR TITLE
AB-354: Include a sleep schedule of 5 seconds after every batch import in musicbrainz importer

### PR DESCRIPTION
**Pull request by rsh7**

### CODE REVIEW

**Comment by rsh7** [comment]
oh, tests are failing. Seems like Jenkins build problem is there.

**Comment by rsh7** [comment]
@brainzbot retest this please

**Comment by paramsingh** [comment]
@rsh7, the tests are failing because I did some changes to the jenkins config for the config changes, once that gets merged rebasing should fix this.

**Comment by rsh7** [comment]
@paramsingh Can you please rebase musicbrainz-integration-gsoc to new master?

**Pull request merged**
