### PR TITLE
AB-120: Dataset creation challenges

### PR DESCRIPTION
**Pull request by gentlecat**
_This is an implementation of my master's project at the UPF. Feel free to share you feedback and ideas._ 💡 

**Currently at https://beta.acousticbrainz.org/challenges/.**

http://tickets.musicbrainz.org/browse/AB-120

### CODE REVIEW

**Comment by gentlecat** [comment]
@brainzbot, test this please.

**Comment by alastair** [comment]
We discussed that we should have a leaderboard of a challenge even if it hasn't finished.

**Comment by gentlecat** [comment]
https://blog.musicbrainz.org/2016/07/12/dataset-creation-challenges-in-acousticbrainz/

**Comment by alastair** [comment]
This is ready to merge, right?

**Comment by gentlecat** [comment]
Right. Was running on beta for a long time now.

**Comment by gentlecat** [comment]
There seem to be some issues with high level output. Tests need to be updated.

**Comment by gentlecat** [comment]
I'll close this. All the code is still in the branch if it's ever needed.

**Pull request closed without merging**
