### PR TITLE
Use a wrapper to call sql scripts in admin

### PR DESCRIPTION
**Pull request by alastair**
Fixes http://tickets.musicbrainz.org/browse/AB-83

### CODE REVIEW

**Comment by gentlecat** [comment]
:+1: :ship:

**Comment by alastair** [comment]
We should put this in other brainzes. Do you want to do this?

**Comment by gentlecat** [comment]
I can do that, but not today. Need to finish some MusicBrainz stuff.

**Comment by alastair** [comment]
no problem

**Pull request merged**
