### PR TITLE
Add working directory as volume to all docker containers

### PR DESCRIPTION
**Pull request by alastair**
This is so that changes in the code can be reflected immediately in the containers without having to rebuild them

### CODE REVIEW

**Comment by alastair** [comment]
In that case we should put the compiled tools and data files somewhere else, and keep /code for code. I'll look into it.

**Comment by alastair** [comment]
Now we install the hl extractor to /usr/local/bin to not conflict with the volume mount. @paramsingh does this look good?

**Comment by paramsingh** [comment]
@brainzbot retest this please

**Comment by paramsingh** [comment]
seems like the model file on essentia.upf.edu is buggy?

```
☁  ~   curl --silent -o models.tar.gz http://essentia.upf.edu/documentation/svm_models/essentia-extractor-svm_models-v2.1_beta1.tar.gz
☁  ~  tar -xvzf models.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
☁  ~  
```

**Comment by alastair** [comment]
gah, I made the change but didn't commit it: we recently added https to the essentia URL + a redirect so we need curl -L, fixing it now

**Pull request merged**
