### PR TITLE
AB-114: Replace toma.hk embed with youtube search

### PR DESCRIPTION
**Pull request by alastair**
http://tickets.musicbrainz.org/browse/AB-114

### CODE REVIEW

**Comment by gentlecat** [comment]
:boom:

**Comment by alastair** [comment]
We can set width and height on the iframe. Can you make a suggestion?

**Comment by gentlecat** [comment]
200px is the minimum value according to https://developers.google.com/youtube/player_parameters. So I'd say adjust it to fill up the space.
```html
<iframe width="200" height="200" ...
```

**Comment by gentlecat** [comment]
And you can set width to `100%` and let our styling handle the rest. It would probably work better this way on mobile layouts.

**Pull request merged**
