### PR TITLE
AB-67: Use logging handler from BrainzUtils

### PR DESCRIPTION
**Pull request by abhi-ohri**
AcousticBrainz is still using its old, custom version instead of using the loggers.py code from BrainzUtils while other MetaBrainz projects have been migrated to BrainzUtils. Therefore, I have migrated from local logging module to BrainzUtils.
**JIRA Ticket:** [AB-67](https://tickets.metabrainz.org/browse/AB-67)

### CODE REVIEW

**Comment by abhi-ohri** [comment]
@paramsingh I went through details of build fail. It says **No Test Report files found - Configuration error**. Is it due to error on my side.

**Comment by paramsingh** [comment]
```
Traceback (most recent call last):
  File "manage.py", line 216, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 256, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/usr/local/lib/python2.7/site-packages/flask/cli.py", line 229, in load_app
    rv = self.create_app(self)
  File "/code/webserver/__init__.py", line 21, in create_app_flaskgroup
    return create_app(debug=True)
  File "/code/webserver/__init__.py", line 60, in create_app
    sentry_config=app.config.get('LOG_SENTRY')
  File "/usr/local/lib/python2.7/site-packages/brainzutils/flask/__init__.py", line 83, in init_loggers
    loggers.add_file_handler(self, **file_config)
TypeError: add_file_handler() argument after ** must be a mapping, not str
```

This is the error I see from https://ci.metabrainz.org/job/acousticbrainz-server/339/console

You can run `./test.sh` to run tests locally.

**Comment by paramsingh** [comment]
The configuration values needed for the CustomFlask init loggers are different. See this for example: https://github.com/metabrainz/critiquebrainz/blob/master/custom_config.py.example#L11

You'll have to make changes to config.py.sample.

**Comment by alastair** [comment]
@abhi-ohri thanks for the contribution! I'm out this week but will try and look at this patch next week for you

**Comment by alastair** [comment]
thanks!

**Pull request merged**
